app = "cloud-storage-backend-heroku"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
[[services.ports]]
handlers = ["tls", "http"]

[experimental]
allowed_public_ports = []
